version: '3.8'
services:
  dify-web:
    image: langgenius/dify-web:latest
    ports:
      - "${PORT:-80}:3000"  # Railway sẽ map PORT -> 3000
    environment:
      - EDITION=SELF_HOSTED
      - API_URL=http://dify-api:5001
    depends_on:
      - dify-api
      - redis

  dify-api:
    image: langgenius/dify-api:latest
    ports:
      - "5001:5001"
    environment:
      # Supabase connection
      - DATABASE_URL=postgresql://postgres:Thuphuong309309@@db.qfvvbcjpihlgpbwglhpu.supabase.co:5432/postgres
      - DB_HOST=db.qfvvbcjpihlgpbwglhpu.supabase.co
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=[YOUR-PASSWORD]
      - DB_DATABASE=postgres
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:6-alpine